# general settings
# Claculate on 720P
# For TSSR-L model: Params: 5.6M
name: TSSR_b64c32n4_500K_DF2K_x5_L1_0.05FFT
model_type: SRModel # Use RealGANModel for GAN training
scale: 5
num_gpu: 1 # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: DF2K
    type: PairedImageDataset
    dataroot_gt: F:/Datasets/SuperResolution/DeepSR_real/DF2K_train_HR
    dataroot_lq: F:/Datasets/SuperResolution/DeepSR_real/DF2K_train_LR_real/X5
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 320
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 12 # Adjust based on your system
    batch_size_per_gpu: 256 #4096 #
    dataset_enlarge_ratio: 1
    prefetch_mode:  cuda #~ #  Use prefetch for better performance on GPU
    pin_memory: true #false # 

  # we use multiple validation datasets. The SR benchmark datasets can be download from: https://cv.snu.ac.kr/research/EDSR/benchmark.tar
  val:
    name: DIV2K_val100
    type: PairedImageDataset
    dataroot_gt: F:/Datasets/SuperResolution/DeepSR_real/DF2K_val_HR
    dataroot_lq: F:/Datasets/SuperResolution/DeepSR_real/DF2K_val_LR_real/X5
    filename_tmpl: '{}'
    io_backend:
      type: disk

# network structures
network_g:
  type: TSSR
  dim: 32
  n_blocks: 4
  upscaling_factor: 5

# path
path:
  pretrain_network_g: ~ # F:/SAFMN/experiments/pretrained_models/net_g_latest.pth # You can specify a pretrained model path here
  strict_load_g: false
  pretrain_network_d: ~
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-3
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [500000]
    restart_weights: [1]
    eta_min: !!float 1e-5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  fft_opt:
    type: FFTLoss
    loss_weight: 0.1
    reduction: mean

# validation settings
val:
  val_freq: !!float 1000
  save_img: False
  pbar: False

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 3
      test_y_channel: False
      better: higher  # the higher, the better. Default: higher
    # ssim:
    #   type: calculate_ssim
    #   crop_border: 3
    #   test_y_channel: False
    #   better: higher  # the higher, the better. Default: higher

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
